name: publish action

on:
  push:
    tags:
    - 'v*'

jobs:
  publish: 
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
    steps:
      - name: checkout repo
        uses: actions/checkout@master

      - name: setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node-version }}

      - name: npm install
        run: npm install
        env:
          CI: true

      - name: unit test
        run: npm run test
        env: 
          CI: true

      - name: report codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: false

      - name: build dist
        run: npm run dist
        env:
          CI: true

      - name: npm publish
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
